name: PR title

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]
    types: [opened, edited, reopened, synchronize]

permissions:
  pull-requests: read

jobs:
  title:
    name: PR title
    uses: FerrLabs/.github/.github/workflows/reusable-pr-title.yml@3df97ce594e954bfed6db38189bcad25452ad034 # main
